Version: 2.0.0
Host: localhost
Port: 5432
User: palette_etl_user
Password: palette123
Database: palette
Schema: palette
WorkflowFilename: workflow_reporting.yml
Logfilename: insight-reporting.log
ConsoleLog: False