Version: 2.0.1
Host: localhost
Port: 5432
User: palette_etl_user
Password: palette123
Database: palette
Schema: palette
WorkflowFilename: /etc/palette-insight-server/workflow_reporting_delta.yml
Logfilename: /var/log/insight-reporting-framework/reporting_delta.log
ConsoleLog: False