Version: 2.1.0
Host: localhost
Port: 5432
User: palette_etl_user
Password: palette123
Database: palette
Schema: palette
WorkflowFilename: /etc/palette-insight-server/workflow_reporting.yml
Logfilename: /var/log/insight-reporting-framework/reporting.log
ConsoleLog: False
WorkflowType: Daily
MaintenanceLogFilename: /var/log/insight-toolkit/db_maintenance.log
LoadControlLogFilename: /var/log/insight-toolkit/loadctrl.log