-
  name:  Setting search_path to {{Schema}}
  query: set search_path={{Schema}}
-
  name:  Run test
  query: select test_py('{{Schema}}')
-
  name:  Another test run
  query: select test_py('{{Schema}}')
