- set search_path={{Schema}}
- select * from p_interactor_session limit 10
-
  - select test_py('{{Schema}}')
  - select test_py('{{Schema}}')
  - select test_py('{{Schema}}')
- select test_py('{{Schema}}')
