- set search_path=#schema_name#
- select test_py(#schema_name#)
-
  - select test_py(#schema_name#)
  - select test_py(#schema_name#)
  - select test_py(#schema_name#)
- select test_py(#schema_name#)
